/* tslint:disable */
/* eslint-disable */
/**
 * Questionnaire Api
 * Patient questionnaire management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xandelt1@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionnaireQuestion
 */
export interface QuestionnaireQuestion {
    /**
     * Question ID
     * @type {number}
     * @memberof QuestionnaireQuestion
     */
    id: number;
    /**
     * Answer text
     * @type {string}
     * @memberof QuestionnaireQuestion
     */
    answer: string;
}

/**
 * Check if a given object implements the QuestionnaireQuestion interface.
 */
export function instanceOfQuestionnaireQuestion(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "answer" in value;

    return isInstance;
}

export function QuestionnaireQuestionFromJSON(json: any): QuestionnaireQuestion {
    return QuestionnaireQuestionFromJSONTyped(json, false);
}

export function QuestionnaireQuestionFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireQuestion {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'answer': json['answer'],
    };
}

export function QuestionnaireQuestionToJSON(value?: QuestionnaireQuestion | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'answer': value.answer,
    };
}

