/* tslint:disable */
/* eslint-disable */
/**
 * Questionnaire Api
 * Patient questionnaire management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xandelt1@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Questionnaire,
} from '../models';
import {
    QuestionnaireFromJSON,
    QuestionnaireToJSON,
} from '../models';

export interface DeleteQuestionnaireEntryRequest {
    ambulanceId: string;
    entryId: string;
}

export interface GetQuestionnaireEntriesRequest {
    ambulanceId: string;
}

export interface GetQuestionnaireEntryRequest {
    ambulanceId: string;
    entryId: string;
}

export interface UpdateQuestionnaireEntryRequest {
    ambulanceId: string;
    entryId: string;
    questionnaire: Questionnaire;
}

/**
 * QuestionnaireApi - interface
 *
 * @export
 * @interface QuestionnaireApiInterface
 */
export interface QuestionnaireApiInterface {
    /**
     *
     * @summary Odstráni konkrétny dotazník
     * @param {string} ambulanceId
     * @param {string} entryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionnaireApiInterface
     */
    deleteQuestionnaireEntryRaw(requestParameters: DeleteQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Odstráni konkrétny dotazník
     */
    deleteQuestionnaireEntry(requestParameters: DeleteQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     *
     * @summary Provides the ambulance questionnaire entries
     * @param {string} ambulanceId ID ambulancie
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionnaireApiInterface
     */
    getQuestionnaireEntriesRaw(requestParameters: GetQuestionnaireEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Questionnaire>>>;

    /**
     * Provides the ambulance questionnaire entries
     */
    getQuestionnaireEntries(requestParameters: GetQuestionnaireEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Questionnaire>>;

    /**
     *
     * @summary Poskytne detail konkrétneho dotazníka
     * @param {string} ambulanceId
     * @param {string} entryId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionnaireApiInterface
     */
    getQuestionnaireEntryRaw(requestParameters: GetQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Questionnaire>>;

    /**
     * Poskytne detail konkrétneho dotazníka
     */
    getQuestionnaireEntry(requestParameters: GetQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Questionnaire>;

    /**
     *
     * @summary Aktualizuje konkrétny dotazník
     * @param {string} ambulanceId
     * @param {string} entryId
     * @param {Questionnaire} questionnaire
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionnaireApiInterface
     */
    updateQuestionnaireEntryRaw(requestParameters: UpdateQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Questionnaire>>;

    /**
     * Aktualizuje konkrétny dotazník
     */
    updateQuestionnaireEntry(requestParameters: UpdateQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Questionnaire>;

}

/**
 *
 */
export class QuestionnaireApi extends runtime.BaseAPI implements QuestionnaireApiInterface {

    /**
     * Odstráni konkrétny dotazník
     */
    async deleteQuestionnaireEntryRaw(requestParameters: DeleteQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling deleteQuestionnaireEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling deleteQuestionnaireEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/questionnaire/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Odstráni konkrétny dotazník
     */
    async deleteQuestionnaireEntry(requestParameters: DeleteQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteQuestionnaireEntryRaw(requestParameters, initOverrides);
    }

    /**
     * Provides the ambulance questionnaire entries
     */
    async getQuestionnaireEntriesRaw(requestParameters: GetQuestionnaireEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Questionnaire>>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getQuestionnaireEntries.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/questionnaire/{ambulanceId}/entries`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionnaireFromJSON));
    }

    /**
     * Provides the ambulance questionnaire entries
     */
    async getQuestionnaireEntries(requestParameters: GetQuestionnaireEntriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Questionnaire>> {
        const response = await this.getQuestionnaireEntriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Poskytne detail konkrétneho dotazníka
     */
    async getQuestionnaireEntryRaw(requestParameters: GetQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Questionnaire>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling getQuestionnaireEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling getQuestionnaireEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/questionnaire/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionnaireFromJSON(jsonValue));
    }

    /**
     * Poskytne detail konkrétneho dotazníka
     */
    async getQuestionnaireEntry(requestParameters: GetQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Questionnaire> {
        const response = await this.getQuestionnaireEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aktualizuje konkrétny dotazník
     */
    async updateQuestionnaireEntryRaw(requestParameters: UpdateQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Questionnaire>> {
        if (requestParameters.ambulanceId === null || requestParameters.ambulanceId === undefined) {
            throw new runtime.RequiredError('ambulanceId','Required parameter requestParameters.ambulanceId was null or undefined when calling updateQuestionnaireEntry.');
        }

        if (requestParameters.entryId === null || requestParameters.entryId === undefined) {
            throw new runtime.RequiredError('entryId','Required parameter requestParameters.entryId was null or undefined when calling updateQuestionnaireEntry.');
        }

        if (requestParameters.questionnaire === null || requestParameters.questionnaire === undefined) {
            throw new runtime.RequiredError('questionnaire','Required parameter requestParameters.questionnaire was null or undefined when calling updateQuestionnaireEntry.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/questionnaire/{ambulanceId}/entries/{entryId}`.replace(`{${"ambulanceId"}}`, encodeURIComponent(String(requestParameters.ambulanceId))).replace(`{${"entryId"}}`, encodeURIComponent(String(requestParameters.entryId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: QuestionnaireToJSON(requestParameters.questionnaire),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuestionnaireFromJSON(jsonValue));
    }

    /**
     * Aktualizuje konkrétny dotazník
     */
    async updateQuestionnaireEntry(requestParameters: UpdateQuestionnaireEntryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Questionnaire> {
        const response = await this.updateQuestionnaireEntryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
