/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AndelProjectQList {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLAndelProjectQListElement extends Components.AndelProjectQList, HTMLStencilElement {
    }
    var HTMLAndelProjectQListElement: {
        prototype: HTMLAndelProjectQListElement;
        new (): HTMLAndelProjectQListElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "andel-project-q-list": HTMLAndelProjectQListElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AndelProjectQList {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "andel-project-q-list": AndelProjectQList;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "andel-project-q-list": LocalJSX.AndelProjectQList & JSXBase.HTMLAttributes<HTMLAndelProjectQListElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
